<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>net.unsun.infrastructure</groupId>
  <artifactId>framework</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>springcloud</name>

  <modules>
    <module>framework-base</module>
  </modules>

  <properties>
    <maven.compiler.source>11</maven.compiler.source>
    <maven.compiler.target>11</maven.compiler.target>
    <maven.compiler.release>11</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

    <!-- Spring Boot 版本 -->
    <spring.boot.version>2.2.1.RELEASE</spring.boot.version>
    <!-- Spring Cloud 版本 -->
    <spring.cloud.version>Hoxton.RC1</spring.cloud.version>
    <!-- 框架版本 -->
    <framework.version>1.0.0-SNAPSHOT</framework.version>
    <jshyun.rpc.version>1.0.0-SNAPSHOT</jshyun.rpc.version>
    
    <!-- Utils 版本 -->
    <lombok.version>1.18.10</lombok.version>
    <junit.version>4.12</junit.version>
    <log4j.version>2.12.1</log4j.version>
    <fastjson.version>1.2.62</fastjson.version>
    <jsoup.version>1.12.1</jsoup.version>
    <hutool.version>5.0.5</hutool.version>
    <logback.version>1.2.3</logback.version>
    <slf4j.version>1.7.29</slf4j.version>
    
    <!-- MyBatis Plus 版本 -->
    <mybatis.plus.version>3.2.0</mybatis.plus.version>
    <pagehelper.version>1.2.12</pagehelper.version>
    <mysql.connector.version>5.1.47</mysql.connector.version>
    <velocity.version>2.1</velocity.version>
    
    <!-- Feign Util 版本 -->
    <feign.util.version>1.1.0</feign.util.version>
    
    <!-- Swagger 版本 -->
    <springfox.version>2.9.2</springfox.version>
    
    <!-- CGLib 版本 -->
    <cglib.version>3.3.0</cglib.version>
    
    <!-- Redis 配置版本 -->
    <commons.pool2.version>2.7.0</commons.pool2.version>
    <jackson.databind.version>2.10.1</jackson.databind.version>
    <bean.utils.version>1.9.4</bean.utils.version>
    <cglib.nodep.version>3.3.0</cglib.nodep.version>
    <google.collections.version>1.0</google.collections.version>
    
    <!-- 全局事务版本 -->
    <seata.version>1.2.0</seata.version>
    <seata.alibaba.version>2.2.0.RELEASE</seata.alibaba.version>
    
    <!-- Sentinel 版本 -->
    <sentinel.version>1.7.1</sentinel.version>
    <sentinel.alibaba.version>2.2.1.RELEASE</sentinel.alibaba.version>
  </properties>

  <repositories>
    <repository>
      <id>central</id>
      <name>Maven Central</name>
      <url>https://repo1.maven.org/maven2/</url>
      <layout>default</layout>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>
    <repository>
      <id>spring-releases</id>
      <name>Spring Releases</name>
      <url>https://repo.spring.io/release</url>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>
    <repository>
      <id>spring-milestones</id>
      <name>Spring Milestones</name>
      <url>https://repo.spring.io/milestone</url>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>
    <repository>
      <id>spring-snapshots</id>
      <name>Spring Snapshots</name>
      <url>https://repo.spring.io/snapshot</url>
      <releases>
        <enabled>false</enabled>
      </releases>
    </repository>
    <repository>
      <id>nexus-snapshots</id>
      <name>Nexus Snapshots Repository</name>
      <url>http://192.168.10.235:8081/repository/maven-snapshots/</url>
    </repository>
  </repositories>

  <pluginRepositories>
    <pluginRepository>
      <id>central</id>
      <name>Maven Central</name>
      <url>https://repo1.maven.org/maven2/</url>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </pluginRepository>
    <pluginRepository>
      <id>spring-releases</id>
      <name>Spring Releases</name>
      <url>https://repo.spring.io/release</url>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </pluginRepository>
  </pluginRepositories>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>${spring.boot.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-dependencies</artifactId>
        <version>${spring.cloud.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-maven-plugin</artifactId>
          <version>${spring.boot.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.11.0</version>
          <configuration>
            <source>${maven.compiler.source}</source>
            <target>${maven.compiler.target}</target>
            <release>${maven.compiler.release}</release>
            <encoding>${project.build.sourceEncoding}</encoding>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-source-plugin</artifactId>
          <version>3.3.0</version>
          <executions>
            <execution>
              <id>attach-sources</id>
              <goals>
                <goal>jar</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>3.1.1</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-install-plugin</artifactId>
          <version>3.1.1</version>
        </plugin>
      </plugins>
    </pluginManagement>
    
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-source-plugin</artifactId>
      </plugin>
    </plugins>
  </build>

  <profiles>
    <profile>
      <id>deploy-snapshots</id>
      <distributionManagement>
        <snapshotRepository>
          <id>nexus-snapshots</id>
          <name>Nexus Snapshots Repository</name>
          <url>http://192.168.10.235:8081/repository/maven-snapshots/</url>
        </snapshotRepository>
      </distributionManagement>
    </profile>
  </profiles>

</project>
