<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>net.unsun.infrastructure</groupId>
  <artifactId>framework-base</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>framework-base</name>

  <modules>
    <module>base-boot-web</module>
    <module>base-cloud-config</module>
    <module>base-cloud-feign</module>
    <module>base-cloud-zipkin</module>
    <module>base-common-kit</module>
    <module>base-config-starter</module>
    <module>base-data-aggr</module>
    <module>base-data-redis</module>
    <module>base-logging-log4j2</module>
    <module>base-mybatis-plus</module>
    <module>base-mybatis-plus-generator</module>
    <module>base-rabbitmq-rpc</module>
    <module>base-security-starter</module>
    <module>base-sentinel-gateway</module>
    <module>base-spring-test</module>
    <module>base-swagger2</module>
    <module>base-tx-seata</module>
  </modules>

  <properties>
    <maven.compiler.source>11</maven.compiler.source>
    <maven.compiler.target>11</maven.compiler.target>
    <maven.compiler.release>11</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

    <spring.boot.version>2.3.12.RELEASE</spring.boot.version>
    <spring.cloud.version>Hoxton.SR12</spring.cloud.version>
    <springfox.version>2.9.2</springfox.version>
    <hutool.version>5.8.25</hutool.version>
    <fastjson.version>1.2.83</fastjson.version>
    <jsoup.version>1.13.1</jsoup.version>
    <mybatis.plus.version>3.3.2</mybatis.plus.version>
    <mysql.connector.version>8.0.28</mysql.connector.version>
    <pagehelper.version>1.2.13</pagehelper.version>
    <jackson.databind.version>2.11.4</jackson.databind.version>
    <commons.pool2.version>2.11.1</commons.pool2.version>
    <junit.version>4.13.2</junit.version>
    <sentinel.version>1.8.6</sentinel.version>
    <alibaba.cloud.version>2.2.10.RELEASE</alibaba.cloud.version>
    <seata.version>1.5.2</seata.version>
    <seata.alibaba.version>2.2.0.RELEASE</seata.alibaba.version>
    <cglib.version>3.3.0</cglib.version>
    <commons.beanutils.version>1.9.4</commons.beanutils.version>
    <cglib.nodep.version>3.2.10</cglib.nodep.version>
    <google.collections.version>1.0</google.collections.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>${spring.boot.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-dependencies</artifactId>
        <version>${spring.cloud.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>com.baomidou</groupId>
        <artifactId>mybatis-plus-boot-starter</artifactId>
        <version>${mybatis.plus.version}</version>
      </dependency>
      <dependency>
        <groupId>mysql</groupId>
        <artifactId>mysql-connector-java</artifactId>
        <version>${mysql.connector.version}</version>
      </dependency>
      <dependency>
        <groupId>com.github.pagehelper</groupId>
        <artifactId>pagehelper-spring-boot-starter</artifactId>
        <version>${pagehelper.version}</version>
      </dependency>
      <dependency>
        <groupId>io.springfox</groupId>
        <artifactId>springfox-swagger2</artifactId>
        <version>${springfox.version}</version>
      </dependency>
      <dependency>
        <groupId>io.springfox</groupId>
        <artifactId>springfox-swagger-ui</artifactId>
        <version>${springfox.version}</version>
      </dependency>
      
    </dependencies>
  </dependencyManagement>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-maven-plugin</artifactId>
          <version>${spring.boot.version}</version>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.11.0</version>
        <configuration>
          <source>${maven.compiler.source}</source>
          <target>${maven.compiler.target}</target>
          <release>${maven.compiler.release}</release>
          <encoding>${project.build.sourceEncoding}</encoding>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-enforcer-plugin</artifactId>
        <version>3.4.1</version>
        <executions>
          <execution>
            <id>enforce-java</id>
            <goals>
              <goal>enforce</goal>
            </goals>
            <configuration>
              <rules>
                <requireJavaVersion>
                  <version>[11,)</version>
                </requireJavaVersion>
              </rules>
              <fail>true</fail>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>


